from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from .import views

urlpatterns=[
    path('signup/',views.Signup,name="signup"),
    path('logout/',views.Logout,name="logout"),
    path('login/',views.Login,name="login"),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.activate, name='activate'),
    path('reset-password',
         PasswordResetView.as_view(template_name='user/password_reset_form.html'), name='password_reset'),
    path('reset-password/done',
         PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    path('listing/',views.ViewPage,name="listing"),
    path('dashboard/',views.Dashboard,name="dashboard"),
    path('password-change/',views.PasswordChange,name="passwordchange"),
    path('view-profile/<int:id>',views.ViewProfile,name="viewprofile"),
    path('follow-profile/',views.Follow,name="follow"),
    path('complete-registration/',views.Complete_Profile,name="update_profile"),
    path('request-zone/',views.RequestZone,name="requestzone"),
    path('send-request/<int:id>',views.SendRequest,name="sendrequest"),
    path('approved-request/<int:id>',views.ApprovedRequest,name="approvedrequest"),
    path('pending-request/<int:id>',views.PendingRequest,name="pendingrequest"),
    path('delete-request/<int:id>',views.DeleteRequest,name="deleterequest"),
    path('contract-us/',views.Contract,name="contractuse"),
    path('friend-list/',views.FriendsView,name="friends"),
    path('friend-request-view/',views.FriendsRequestView,name="friendsrequest"),
    path('un-friend/<int:id>',views.UnFriend,name="unfriend"),
    path('reject-friend/<int:id>',views.RejectFriend,name="rejectfriend"),
    path('accept-friend/<int:id>',views.AcceptFriend,name="acceptfriend"),
    path('message-view/',views.Messenger,name="messenger"),
    path('send-message/',views.SendMessage,name="sendmessage"),
    path('view-send-message',views.ViewSendMessage,name="sendmessageview"),
    path('send-friend-request/<int:id>',views.AddFriend,name="addfriend"),
    path('reply-message/<int:id>',views.RepliedMessage,name='repliedmessage'),
    path('view-sent-message/<int:id>',views.ViewSendMessageDetails,name="sendmessagedetails"),
    path('success-story/',views.SuccesStory,name="successstory"),
    path('view-success-story/<int:id>',views.viewSuccessstory,name="viewstory"),
    path('like-success-story',views.Likes,name="add_like"),
    path('add-success-story/',views.AddSuccessStory,name="addsuccess"),
    path('story-list/',views.StoryList,name="storylist"),
    path('delete-story/<int:id>',views.DeleteStory,name="deletestory"),
    path('story-update/<int:id>',views.UpdateStory,name="updatestory"),
    path('search-patner/',views.SearchPatner,name="searchpatner"),
    path('success-ratting/<int:id>',views.SuccessRatting,name="successratting"),
    path('update-profile/',views.UpdateP,name="updateprofile"),
]
