# Generated by Django 2.2.7 on 2020-12-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('city', models.CharField(max_length=20, verbose_name='City Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
                ('age', models.PositiveIntegerField(default=18)),
                ('height', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('mother_tongue', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20)),
                ('body_type', models.CharField(blank=True, choices=[('Slim', 'Slim'), ('Faty', 'Faty'), ('Medium', 'Medium')], max_length=12)),
                ('complexion', models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Light Fair', 'Light Fair'), ('Black', 'Black'), ('Light Brown', 'Light Brown'), ('Brown', 'Brown')], max_length=20)),
                ('physical_status', models.CharField(blank=True, max_length=20)),
                ('eating_habit', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non Vegetarian', 'Non Vegetarian'), ('Both', 'Both')], max_length=20)),
                ('drinking_habit', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly')], max_length=20)),
                ('smoking_habit', models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Regularly', 'Regularly')], max_length=20)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Buddhists', 'Buddhists '), ('Buddhists', 'Buddhists '), ('Christians', 'Christians ')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('parents_phone', models.CharField(blank=True, max_length=11)),
                ('whatsapp', models.CharField(blank=True, max_length=11)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('citizenship', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, choices=[('JSC', 'JSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('BBA', 'BBA '), ('MBA', 'MBA '), ('BA', 'BA '), ('BSC', 'BSC '), ('MMBS', 'MMBS '), ('CIVIL', 'CIVIL '), ('DAKIL', 'DAKIL '), ('KAMIL', 'KAMIL '), ('LLB', 'LLB ')], max_length=30)),
                ('education_details', models.TextField(blank=True, max_length=200)),
                ('employed', models.CharField(blank=True, max_length=50)),
                ('occupation', models.TextField(blank=True, max_length=100)),
                ('annual_income', models.PositiveIntegerField(default=0)),
                ('family_Value', models.CharField(blank=True, max_length=30)),
                ('family_type', models.CharField(blank=True, max_length=30)),
                ('family_status', models.CharField(blank=True, max_length=30)),
                ('father_status', models.CharField(blank=True, max_length=30)),
                ('family_location', models.CharField(blank=True, max_length=30)),
                ('about_family', models.TextField(blank=True, max_length=200)),
                ('p_age', models.PositiveIntegerField(default=18)),
                ('p_height', models.PositiveIntegerField(default=0)),
                ('p_weight', models.FloatField(default=0.0)),
                ('p_mother_tongue', models.CharField(blank=True, max_length=30)),
                ('p_physical_status', models.CharField(blank=True, max_length=20)),
                ('p_eating_habit', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non Vegetarian', 'Non Vegetarian'), ('Both', 'Both')], max_length=20)),
                ('p_drinking_habit', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly')], max_length=20)),
                ('p_smoking_habit', models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Regularly', 'Regularly')], max_length=20)),
                ('p_religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Buddhists', 'Buddhists '), ('Buddhists', 'Buddhists '), ('Christians', 'Christians ')], max_length=20)),
                ('p_education', models.CharField(blank=True, choices=[('JSC', 'JSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('BBA', 'BBA '), ('MBA', 'MBA '), ('BA', 'BA '), ('BSC', 'BSC '), ('MMBS', 'MMBS '), ('CIVIL', 'CIVIL '), ('DAKIL', 'DAKIL '), ('KAMIL', 'KAMIL '), ('LLB', 'LLB ')], max_length=30)),
                ('p_occupation', models.TextField(blank=True, max_length=100)),
                ('p_annual_income', models.PositiveIntegerField(default=0)),
                ('p_country', models.CharField(blank=True, max_length=30)),
                ('p_citizenship', models.CharField(blank=True, max_length=30)),
                ('p_state', models.CharField(blank=True, max_length=30)),
                ('p_city', models.TextField(blank=True, max_length=100)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
