# Generated by Django 2.2.7 on 2020-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
