# Generated by Django 2.2.7 on 2021-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('JSC', 'JSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('BBA', 'BBA '), ('MBA', 'MBA '), ('BA', 'BA '), ('BSC', 'BSC '), ('MBBS', 'MBBS '), ('CIVIL', 'CIVIL '), ('DAKIL', 'DAKIL '), ('KAMIL', 'KAMIL '), ('LLB', 'LLB ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_education',
            field=models.CharField(blank=True, choices=[('JSC', 'JSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('BBA', 'BBA '), ('MBA', 'MBA '), ('BA', 'BA '), ('BSC', 'BSC '), ('MBBS', 'MBBS '), ('CIVIL', 'CIVIL '), ('DAKIL', 'DAKIL '), ('KAMIL', 'KAMIL '), ('LLB', 'LLB ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Buddhists', 'Buddhists '), ('Christians', 'Christians ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Buddhists', 'Buddhists '), ('Christians', 'Christians ')], max_length=20),
        ),
    ]
