# Generated by Django 2.2.7 on 2021-01-01 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='viewer',
            field=models.ManyToManyField(blank=True, related_name='viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
