# Generated by Django 2.2.7 on 2021-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210104_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='contract',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept')], max_length=12),
        ),
    ]
