# Generated by Django 2.2.7 on 2021-01-04 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210104_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='see_contract',
            field=models.ManyToManyField(blank=True, related_name='see_contract', to=settings.AUTH_USER_MODEL),
        ),
    ]
