# Generated by Django 2.2.7 on 2021-01-04 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_send_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_request',
            field=models.ManyToManyField(blank=True, related_name='receive_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
