# Generated by Django 2.2.7 on 2021-01-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_receive_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=500)),
                ('replied', models.BooleanField(default=False, max_length=10)),
                ('receive_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
