# Generated by Django 2.2.7 on 2021-01-06 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_contractus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='friend_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_send',
            field=models.ManyToManyField(blank=True, related_name='friend_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
