# Generated by Django 2.2.7 on 2021-01-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210106_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='subject', max_length=50)),
                ('sender_msg', models.TextField(max_length=300)),
                ('receiver_msg', models.TextField(max_length=300)),
                ('send_on', models.DateTimeField(auto_now=True)),
                ('reply_on', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
