# Generated by Django 2.2.7 on 2021-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210110_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='successStory/'),
        ),
    ]
