# Generated by Django 2.2.7 on 2021-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_successstory_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='photo',
            field=models.ImageField(default='success.jpg', upload_to='successStory/'),
        ),
    ]
