# Generated by Django 2.2.7 on 2021-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210115_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Reputed', 'Reputed'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=30),
        ),
    ]
