# Generated by Django 2.2.7 on 2021-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210115_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_body_type',
            field=models.CharField(blank=True, choices=[('Slim', 'Slim'), ('Faty', 'Faty'), ('Medium', 'Medium')], max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_complexion',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Light Fair', 'Light Fair'), ('Black', 'Black'), ('Light Brown', 'Light Brown'), ('Brown', 'Brown')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_family_status',
            field=models.CharField(blank=True, choices=[('Reputed', 'Reputed'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=30),
        ),
    ]
